### PR TITLE
Fixed the unexpected insufficient funds error in drain checks

### LINKED ISSUE #259: Analysis with `forbidFailures` includes executions with errors in the action phase
Here is our TON drain checker:
```
#include "imports/stdlib.fc";
#include "imports/tsa_functions.fc";

global slice initial_sender;
global slice contract_address;
global int initial_value;
global int received_value;

() on_internal_message_send(int balance, int msg_value, cell in_msg_full, slice msg_body, int input_id) impure method_id {
    slice cs = in_msg_full.begin_parse();
    cs~load_uint(4); ;; flags
    initial_sender = cs~load_msg_addr(); ;; src
    contract_address = cs~load_msg_addr(); ;; dst
    initial_value = cs~load_coins(); ;; value

    cell c4 = tsa_get_c4(1);
    tsa_make_address_random(initial_sender);
    tsa_make_slice_independent_from_random_addresses(c4.begin_parse());
    tsa_make_slice_independent_from_random_addresses(contract_address);
}

() on_out_message(cell msg_full, slice msg_body, int receiver_contract_id, int sender_contract_id) impure method_id {
    if ((sender_contract_id != 1) | (receiver_contract_id != -1)) {
        return ();
    }

    slice cs = msg_full.begin_parse();
    cs~skip_bits(4); ;; message headers
    cs~load_msg_addr(); ;; src address
    slice dest = cs~load_msg_addr();
    int value = cs~load_grams();

    if (equal_slice_bits(dest, initial_sender)) {
        received_value += value;
    }
}

() main() impure {
    received_value = 0;

    tsa_forbid_failures();

    slice ds = get_data().begin_parse();
    int nonce_method_id = ds~load_uint(32);
    int nonce_value = ds~load_uint(64);
    if (nonce_method_id != 0) {
        int nonce = tsa_call_1_0(1, nonce_method_id);
        tsa_assert(nonce == nonce_value);
    }

    tsa_send_internal_message(1, 0);

    tsa_allow_failures();

    throw_if(1000, received_value > initial_value);
}
```

`tsa_send_internal_message` is called between `tsa_forbid_failures` and `tsa_allow_failures`, so we should exclude exceptional states.

But an exection with the error `TVM insufficient funds while processing messages sent by contract 1` is found.

### PR DESCRIPTION
**Pull request by metametamoon**
Closes #259.

Apparently the error is specific to insufficient funds error due to the way the failure was set previously. 
This PR aims to fix this.

### CODE REVIEW

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmArtificialInstInterpreter.kt [hunk 1]
```diff
@@ -395,14 +396,7 @@ class TvmArtificialInstInterpreter(
...
                     calcOnState {
-                        val failure =
-                            TvmFailure(
-                                actionsHandlingResult.failure,
-                                TvmFailureType.UnknownError,
-                                phase,
-                                pathNode,
-                            )
-                        newStmt(TsaArtificialExitInst(stmt.computePhaseResult, failure, lastStmt.location))
+                        ctx.setFailure(actionsHandlingResult.failure, level = TvmFailureType.RealError)(this)
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmArtificialInstInterpreter.kt]: We use `TvmFailureType.RealError` only for cell underflow. Here, please use `TvmFailureType.UnknownError` (or make it default value in `ctx.setFailure`)
