### PR TITLE
Input dict implementation

### LINKED ISSUE #130: Failing tests for input dict operations
Test report for `InputDictIntegrationTest` (which is for now ignored in the main branch):

```
InputDictIntegrationTest > all dictionary tests() > set-delete/add-does-not-override-old-key.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/delete-and-get-consistency.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/ite-get.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/delete-does-not-override-other-keys.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/set-does-not-override-other-keys.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/dictdelget-return-value.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/set-and-get-consistency.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/set-overrides-old-value.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/set-overrides-old-key.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/dictdelget-after-set-return-value.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/dictdelget-after-delete-noop.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/dictdel-stores-int.fc PASSED
InputDictIntegrationTest > all dictionary tests() > set-delete/delete-overrides-old-key.fc PASSED
InputDictIntegrationTest > all dictionary tests() > queries/next-prev-is-id.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:40
InputDictIntegrationTest > all dictionary tests() > queries/get-next-and-get-consistency-2.fc PASSED
InputDictIntegrationTest > all dictionary tests() > queries/get-next-and-get-consistency.fc PASSED
InputDictIntegrationTest > all dictionary tests() > queries/get-next-is-function.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:40
InputDictIntegrationTest > all dictionary tests() > queries/get-max-returns-none-implies-empty.fc PASSED
InputDictIntegrationTest > all dictionary tests() > queries/get-prev-is-function.fc PASSED
InputDictIntegrationTest > all dictionary tests() > queries/get-max-returns-max.fc PASSED
InputDictIntegrationTest > all dictionary tests() > queries/get-max-returns-max-reordered.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:40
InputDictIntegrationTest > all dictionary tests() > queries/get-is-id.fc PASSED
InputDictIntegrationTest > all dictionary tests() > queries/get-next-is-function-not-found.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:45
InputDictIntegrationTest > all dictionary tests() > min-max-delete/min-delete.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:40
InputDictIntegrationTest > all dictionary tests() > signed/wallet-v5-simple-signed.fc PASSED
InputDictIntegrationTest > all dictionary tests() > signed/get-next-is-function.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:40
InputDictIntegrationTest > all dictionary tests() > signed/idict-min-delete-iter-3-256.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:40
InputDictIntegrationTest > all dictionary tests() > signed/get-is-id.fc PASSED
InputDictIntegrationTest > all dictionary tests() > complex/set-increases-size-1.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:45
InputDictIntegrationTest > all dictionary tests() > complex/udict-min-delete-iter-3-256.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:40
InputDictIntegrationTest > all dictionary tests() > complex/udict-get-delete-symbolic-256.fc PASSED
InputDictIntegrationTest > all dictionary tests() > complex/udict-get-delete-existing.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:45
InputDictIntegrationTest > all dictionary tests() > complex/filter.fc PASSED
InputDictIntegrationTest > all dictionary tests() > complex/wallet-v5-simple.fc PASSED
InputDictIntegrationTest > all dictionary tests() > complex/udict-get-delete-returns-non-null.fc PASSED
InputDictIntegrationTest > all dictionary tests() > complex/set-increases-size-2.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:45
InputDictIntegrationTest > all dictionary tests() > complex/set-increases-size-3.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:45
InputDictIntegrationTest > all dictionary tests() > complex/udict-get-delete-existing-256.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:45
InputDictIntegrationTest > all dictionary tests() > complex/filter-256.fc PASSED
InputDictIntegrationTest > all dictionary tests() > complex/udict-min-delete-iter-2-256.fc FAILED
    java.lang.IllegalStateException at IntegrationTestFramework.kt:40
```

### PR DESCRIPTION
**Pull request by metametamoon**
Closes #130

### CODE REVIEW

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmInputDict.kt [hunk 1]
```diff
@@ -0,0 +1,456 @@
...
+import kotlinx.collections.immutable.persistentListOf
+import kotlinx.collections.immutable.toPersistentList
+import org.usvm.UBoolExpr
+import org.usvm.UExpr
+import org.usvm.machine.TvmContext
+import org.usvm.machine.splitHeadTail
+
+typealias KeySort = TvmContext.TvmCellDataSort
+typealias K = UExpr<KeySort>
+typealias ConstraintSet = PersistentList<UBoolExpr>
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmInputDict.kt]: If this is set, maybe it should be `PersistentSet`?

Also, I am not sure if this type alias simplifies the code

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 2]
```diff
@@ -1376,6 +1480,35 @@ class TvmDictOperationInterpreter(
         val dictId = DictId(keyLength)
         val resultDict = scope.calcOnState { memory.allocConcrete(TvmDictCellType) }
 
+        val keySort = ctx.mkBvSort(keyLength.toUInt())
+        val allSetEntries =
+            scope.calcOnStateCtx {
+                dictCellRef?.let { memory.setEntries(it, dictId, keySort, DictKeyInfo) }
+            }
+        if (allSetEntries != null && allSetEntries.isInput) {
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Have you checked that `allSetEntries.isInput` works as expected?

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 3]
```diff
@@ -1376,6 +1480,35 @@ class TvmDictOperationInterpreter(
...
+            if (getOldValue) {
+                error("unsupported getting old value in input dicts `set` operation")
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Isn't it `TODO`?

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 4]
```diff
@@ -1376,6 +1480,35 @@ class TvmDictOperationInterpreter(
...
+            }
+            val dictConcreteRef =
+                dictCellRef as? UConcreteHeapRef
+                    ?: error("unsupported")
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Are you going to support case of ite?

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 5]
```diff
@@ -1893,13 +2212,22 @@ class TvmDictOperationInterpreter(
...
         }
     }
 
+    private fun TvmState.readInputDictionary(
+        dictConcreteRef: UConcreteHeapRef,
+    ): Pair<InputDict, InputDictRootInformation> {
+        val inputDict = inputDictionaryStorage.memory[dictConcreteRef] ?: InputDict()
+        val rootInputDictInfo =
+            inputDictionaryStorage.inputDicts[inputDict.rootInputDictId] ?: InputDictRootInformation()
+        return Pair(inputDict, rootInputDictInfo)
```
[the remark this answers is not in the document]
Comment (tochilinak) [reply tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Ok, this solution seems fine

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/LazyUniversalQuantifierConstraint.kt [hunk 6]
```diff
@@ -0,0 +1,68 @@
+package org.usvm.machine.interpreter.inputdict
+
+import kotlinx.collections.immutable.PersistentList
+import org.usvm.UBoolExpr
+import org.usvm.machine.TvmContext
+
+sealed interface LazyUniversalQuantifierConstraint {
+    val modifications: PersistentList<Modification>
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/LazyUniversalQuantifierConstraint.kt]: Why is it needed here?

File: tsa-core/src/main/kotlin/org/usvm/machine/state/TvmSliceUtils.kt [hunk 7]
```diff
@@ -1488,21 +1488,26 @@ fun TvmState.readSliceDataPos(slice: UHeapRef) = fieldManagers.cellDataLengthFie
...
 )
 
 // for debugging
 @Suppress("unused")
 fun TvmState.readSliceFull(slice: UHeapRef): SliceReadData {
     val dataPos = readSliceDataPos(slice)
+    val refPos = readSliceRefPos(slice)
     val cell = readSliceCell(slice)
-    val cellData = fieldManagers.cellDataFieldManager.readCellDataWithoutAsserts(this, cell)
+    val cellData = runCatching { fieldManagers.cellDataFieldManager.readCellDataWithoutAsserts(this, cell) }.getOrNull()
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/state/TvmSliceUtils.kt]: This seems very wrong

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 8]
```diff
@@ -1515,27 +1677,100 @@ class TvmDictOperationInterpreter(
...
+                scope.assert(scope.ctx.mkAnd(cs))
+                    ?: return
+                scope.calcOnStateCtx {
+                    inputDictionaryStorage = inputDictionaryStorage.set(dictConcreteRef, inputDict, updatedRootInfo)
+                }
+                keyExists
+            } else {
+                scope.calcOnState {
+                    dictContainsKey(dictCellRef, dictId, key)
+                }
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: It is really not obvious that this function can be called only on allocated dict. At least rename it, better to make a general function

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 9]
```diff
@@ -1669,15 +1998,76 @@ class TvmDictOperationInterpreter(
...
+                    )
+            }
+
+            val value = scope.calcOnState { dictGetValue(dictCellRef, dictId, keyResultSymbol.expr) }
+            val unwrappedValue =
+                unwrapDictValue(scope, value, valueType)
+                    ?: return
+
+            assertDictValueDoesNotOverflow(scope, dictId, value)
+                ?: return
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Cannot we make this assertion with your universal quantifiers? Then, we probably won't even need this function.

**Review by tochilinak — CHANGES_REQUESTED** [review]

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 10]
```diff
@@ -1515,27 +1677,100 @@ class TvmDictOperationInterpreter(
...
+                key,
+                nullDefaultValue,
+                inst,
+                valueType,
+            )
+        } else {
+            scope.doWithConditions(actions) { dictCellRef ->
+                doDictGetImpl(this, this@with, keyLength, dictCellRef, keyKind, key, nullDefaultValue, inst, valueType)
+            }
+        }
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: If you make `doWithConditions` with one variant (that has `true` guard), fork doesn't actually happen. It just changes step scope. So need for this

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 11]
```diff
@@ -1515,27 +1677,100 @@ class TvmDictOperationInterpreter(
...
+                }
+        if (!isInput) {
+            assertDictIsNotEmpty(scope, dictCellRef, dictId)
+                ?: return
+        }
         val dictContainsKey =
-            scope.calcOnState {
-                dictContainsKey(dictCellRef, dictId, key)
+            if (isInput) {
+                val dictConcreteRef = dictCellRef
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Why?

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 12]
```diff
@@ -1586,8 +1821,86 @@ class TvmDictOperationInterpreter(
 
         assertDictKeyLength(scope, dictCellRef, keyLength)
             ?: return
-        assertDictIsNotEmpty(scope, dictCellRef, dictId)
-            ?: return
+
+        val keySort = ctx.mkBvSort(keyLength.toUInt())
+        val allSetEntries = scope.calcOnStateCtx { memory.setEntries(dictCellRef, dictId, keySort, DictKeyInfo) }
+        val isInput =
+            allSetEntries.isInput || scope.calcOnState { inputDictionaryStorage.memory.keys.contains(dictCellRef) }
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Same

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 13]
```diff
@@ -1586,8 +1821,86 @@ class TvmDictOperationInterpreter(
...
+                        TvmStepScopeManager.ActionOnCondition<Unit>(
+                            {
+                                addOnStack(resultDict, TvmCellType)
+                                addValueOnStack(unwrappedValue, valueType)
+                                addOnStack(ctx.trueValue, TvmIntegerType)
+                                newStmt(inst.nextStmt())
+                            },
+                            false,
+                            exists,
+                            Unit,
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Used named parameters in such cases

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 14]
```diff
@@ -1586,8 +1821,86 @@ class TvmDictOperationInterpreter(
...
+                        ),
+                        TvmStepScopeManager.ActionOnCondition<Unit>(
+                            {
+                                addOnStack(resultDict, TvmCellType)
+                                addOnStack(ctx.falseValue, TvmIntegerType)
+                                newStmt(inst.nextStmt())
+                            },
+                            false,
+                            ctx.mkNot(exists),
+                            Unit,
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Same

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 15]
```diff
@@ -1515,27 +1677,100 @@ class TvmDictOperationInterpreter(
...
+        val isInput =
+            allSetEntries.isInput ||
+                scope.calcOnState {
+                    this.inputDictionaryStorage.memory.keys
+                        .contains(dictCellRef)
+                }
+        if (!isInput) {
+            assertDictIsNotEmpty(scope, dictCellRef, dictId)
+                ?: return
+        }
```
[the remark this answers is not in the document]
Comment (metametamoon) [reply tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: I preserved this logic from the previous version so the code works the same way as before on non-input dictionaries

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 16]
```diff
@@ -1586,8 +1821,86 @@ class TvmDictOperationInterpreter(
...
-            ?: return
+
+        val keySort = ctx.mkBvSort(keyLength.toUInt())
+        val allSetEntries = scope.calcOnStateCtx { memory.setEntries(dictCellRef, dictId, keySort, DictKeyInfo) }
+        val isInput =
+            allSetEntries.isInput || scope.calcOnState { inputDictionaryStorage.memory.keys.contains(dictCellRef) }
+        if (!isInput) {
+            assertDictIsNotEmpty(scope, dictCellRef, dictId)
+                ?: return
+        }
```
[the remark this answers is not in the document]
Comment (metametamoon) [reply tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Same

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt (hunk 4 above)
Comment (metametamoon) [reply tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: I'll postpone the implementation to the other pull request (the corresponding issue is #132)

File: tsa-core/src/main/kotlin/org/usvm/machine/state/TvmSliceUtils.kt (hunk 7 above)
Comment (metametamoon) [reply tsa-core/src/main/kotlin/org/usvm/machine/state/TvmSliceUtils.kt]: Why?

File: tsa-core/src/main/kotlin/org/usvm/test/resolver/TvmTestStateResolver.kt
[the remark this answers is not in the document]
Comment (metametamoon) [reply tsa-core/src/main/kotlin/org/usvm/test/resolver/TvmTestStateResolver.kt]: I added them in `input-dict/hash` resource folder

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmValueFixator.kt [hunk 17]
```diff
@@ -177,37 +183,94 @@ class TvmValueFixator(
...
+                val newConditions =
+                    fixateDictEntries(scope, model, modelRef, dictId, keySort, ref, value)
+                        ?: return@with null
+                result = result and mkAnd(newConditions)
+            } else {
+                val (inputDict, baseInputDict) =
                     scope.calcOnState {
-                        dictGetValue(ref, dictId, key)
+                        val inputDict = inputDictionaryStorage.memory[ref] ?: error("Input dict not found")
+                        val rootInformation =
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmValueFixator.kt]: Better to move input dict fixation to a separate function

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmValueFixator.kt [hunk 18]
```diff
@@ -177,37 +183,94 @@ class TvmValueFixator(
...
+                            inputDictionaryStorage.rootInformation[inputDict.rootInputDictId]
+                                ?: error("Root information not found")
+                        inputDict to rootInformation
                     }
+                val keyEntries = inputDict.getCurrentlyDiscoveredKeys(ctx, baseInputDict)
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmValueFixator.kt]: Is it guaranteed that no new keys will be added?

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 19]
```diff
@@ -1454,6 +1602,99 @@ class TvmDictOperationInterpreter(
...
+                    inputDictionaryStorage =
+                        inputDictionaryStorage.updateRootInputDictionary(baseInputDict.rootInputDictId, rootInformation)
+                }
+                val keyExists = doInputDictHasKey(scope, baseInputDict, KeyType(key, keyKind))?.exists ?: return null
+                val updatedRootInfo =
+                    scope.calcOnState { inputDictionaryStorage.getRootInfoByIdOrThrow(baseInputDict.rootInputDictId) }
+                scope.calcOnState {
+                    inputDictionaryStorage =
+                        inputDictionaryStorage.updateRootInputDictionary(baseInputDict.rootInputDictId, updatedRootInfo)
+                }
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Same question

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 20]
```diff
@@ -1637,18 +1929,154 @@ class TvmDictOperationInterpreter(
...
+                    condition = someKeyExistsAfterDeletion,
+                    paramForDoForAllBlock = resultDictRef,
+                ),
+                TvmStepScopeManager.ActionOnCondition(
+                    action = {},
+                    caseIsExceptional = false,
+                    condition = ctx.mkNot(someKeyExistsAfterDeletion),
+                    paramForDoForAllBlock = ctx.nullValue,
+                ),
+            )
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: This block is misleading. Don't you fork on each variant? If so, why do you assert both conditions? If you assert contradicting constraints, then your state must die.

Do you have tests for this case?

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 21]
```diff
@@ -1806,54 +2325,67 @@ class TvmDictOperationInterpreter(
...
+                allowEq = allowEq,
+                dictId = dictId,
+                valueType = valueType,
+                inst = inst,
+            )
+            return
+        }
 
-        // TODO input keys are not considered
         val storedKeys =
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: I think that processing of allocated dict should also be moved to a separate function (that applies to all dict operations).

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/InputDictionaryStorage.kt [hunk 22]
```diff
@@ -0,0 +1,67 @@
...
+ * each root information unit has an id (local to the [org.usvm.machine.state.TvmState]) that is used
+ * by [InputDict]s to reference it.
+ * Such an architecture allows us to implement the procedure as shown in [set].
+ */
+class InputDictionaryStorage(
+    val memory: PersistentMap<UConcreteHeapRef, InputDict> = persistentMapOf(),
+    val rootInformation: PersistentMap<Int, InputDictRootInformation> = persistentMapOf(),
+) {
+    /**
+     * DEPRECATED
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/InputDictionaryStorage.kt]: Why is it here?

File: tsa-core/src/main/kotlin/org/usvm/test/resolver/TvmTestStateResolver.kt [hunk 23]
```diff
@@ -512,9 +513,15 @@ class TvmTestStateResolver(
             val keySet = mutableSetOf<UExpr<UBvSort>>()
             val resultEntries = mutableMapOf<TvmTestIntegerValue, TvmTestSliceValue>()
 
+            if (dict is UConcreteHeapRef) {
+                val inputDict = state.inputDictionaryStorage.memory[dict]
+                if (inputDict != null) {
+                    return handleInputDict(inputDict, dict, dictId, keyLength, modelRef)
+                }
+            }
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/test/resolver/TvmTestStateResolver.kt]: And what if `dict` is ITE where one of the leaves is input dict? It can be input dict in the model. (You should probably first eval `dict`)

File: tsa-test/src/test/kotlin/org/ton/examples/contracts/ContractsTest.kt [hunk 24]
```diff
@@ -90,7 +90,7 @@ class ContractsTest {
         analyzeFuncContract(walletV4Path, methodsNumber = 7, enableTestGeneration = true)
     }
 
-    @EnabledIfEnvironmentVariable(named = RUN_HARD_TESTS_VAR, matches = RUN_HARD_TESTS_REGEX)
+//    @EnabledIfEnvironmentVariable(named = RUN_HARD_TESTS_VAR, matches = RUN_HARD_TESTS_REGEX)
```
Comment (tochilinak) [inline tsa-test/src/test/kotlin/org/ton/examples/contracts/ContractsTest.kt]: Commented out line

File: tsa-test/src/test/kotlin/org/ton/examples/contracts/ContractsTest.kt [hunk 25]
```diff
@@ -139,7 +139,7 @@ class ContractsTest {
         analyzeFuncContract(bridgePath, methodsNumber = 8, enableTestGeneration = true)
     }
 
-    @EnabledIfEnvironmentVariable(named = RUN_HARD_TESTS_VAR, matches = RUN_HARD_TESTS_REGEX)
+//    @EnabledIfEnvironmentVariable(named = RUN_HARD_TESTS_VAR, matches = RUN_HARD_TESTS_REGEX)
```
Comment (tochilinak) [inline tsa-test/src/test/kotlin/org/ton/examples/contracts/ContractsTest.kt]: Same

**Review by tochilinak — CHANGES_REQUESTED** [review]

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 26]
```diff
@@ -1637,18 +1929,154 @@ class TvmDictOperationInterpreter(
...
+    ) {
+        val dictKeyLength = memory.readField(dictOriginalConcrete, dictKeyLengthField, ctx.sizeSort)
+        memory.writeField(resultDict, dictKeyLengthField, ctx.sizeSort, dictKeyLength, guard = ctx.trueExpr)
+        val dictValueRegionId = TvmDictValueRegionId(dictId, keySort)
+        val dictValueRegion = memory.dictValueRegion(dictValueRegionId)
+        val updatedValues =
+            dictValueRegion
+                .copyRefValues(dictOriginalConcrete, resultDict)
+        memory.setRegion(dictValueRegionId, updatedValues)
+    }
```
[the remark this answers is not in the document]
Comment (metametamoon) [reply tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: We only use the new representation to store the set of keys of the dictionary

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/Modification.kt [hunk 27]
```diff
@@ -0,0 +1,62 @@
...
+    ) : Modification
+
+    data class Store(
+        val key: KeyType,
+        val guard: UBoolExpr,
+    ) : Modification
+}
+
+/** @return the condition that would be of a corresponding key in `getKeys` */
+fun List<Modification>.createKeyCondition(
```
[the remark this answers is not in the document]
Comment (tochilinak) [reply tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/Modification.kt]: Though, with this name, it is not clear why empty list results in `trueExpr`. But the current name is also not very clear

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/Modification.kt [hunk 28]
```diff
@@ -0,0 +1,62 @@
...
+    ctx: TvmContext,
+    t: KExtended,
+): UBoolExpr {
+    val (head, tail) = splitHeadTail() ?: return ctx.trueExpr
+    val prevCond = tail.createKeyCondition(ctx, t)
+    return when (head) {
+        is Modification.Store -> with(ctx) { prevCond or (t eq head.key.toExtendedKey(ctx)) }
+        is Modification.Remove -> with(ctx) { prevCond and (t neq head.key.toExtendedKey(ctx)) }
+    }
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/Modification.kt]: Is it true that if all modifications are `store`, then the result condition is always `trueExpr`? If so, what is supposed to mean?

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/Modification.kt [hunk 29]
```diff
@@ -0,0 +1,62 @@
...
+    data class Store(
+        val key: KeyType,
+        val guard: UBoolExpr,
+    ) : Modification
+}
+
+/** @return the condition that would be of a corresponding key in `getKeys` */
+fun List<Modification>.createKeyCondition(
+    ctx: TvmContext,
+    t: KExtended,
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/Modification.kt]: Is it true that it is assumed that `t` should be in the root dictionary (in its `symbols`)? If so, you should add it as a comment. Or at least give `t` a better name (or both).

File: tsa-core/src/main/kotlin/org/usvm/test/resolver/TvmTestStateResolver.kt (hunk 23 above)
Comment (metametamoon) [reply tsa-core/src/main/kotlin/org/usvm/test/resolver/TvmTestStateResolver.kt]: Fixed it by using only concrete ref

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/LazyUniversalQuantifierConstraint.kt [hunk 30]
```diff
@@ -0,0 +1,100 @@
...
+     * In short - it is used to construct the conditions a key in the root input dictionary R
+     * would have in some other input dictionary P which was constructed by applying modifications
+     * on top of R.
+     * For more information, see [InputDictRootInformation] and
+     * [InputDictRootInformation.addLazyUniversalConstraint].
+     */
+    val modifications: PersistentList<Modification>
+
+    /**
+     * @param symbol is of KExtended sort as all the comparisons must be done on the extended key type
```
[the remark this answers is not in the document]
Comment (metametamoon) [reply tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/LazyUniversalQuantifierConstraint.kt]: I'll use proper markdown references so that renaming will automatically affect the doc.

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmValueFixator.kt [hunk 31]
```diff
@@ -177,37 +185,122 @@ class TvmValueFixator(
...
-                    val valueConstraint =
-                        fixateConcreteValue(scope, entryValue, concreteValue)
-                            ?: return@with null
-                    result = result and keyContains and valueConstraint and keyConstraint
+    private fun TvmContext.fixateInputDictEntries(
+        scope: TvmStepScopeManager,
+        inputDict: InputDict,
+        ref: UHeapRef,
+        dictId: DictId,
+        model: UModelBase<TvmType>,
```
[the remark this answers is not in the document]
Comment (tochilinak) [reply tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmValueFixator.kt]: Here, we probably won't encounter this case, but in general it is always better not to access model directly

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmValueFixator.kt [hunk 32]
```diff
@@ -177,37 +185,122 @@ class TvmValueFixator(
...
+                asserts.add(valueConstraint)
             }
+        }
+        return asserts
+    }
 
-            return result
+    private fun TvmContext.fixateAllocatedDictEntries(
+        scope: TvmStepScopeManager,
+        model: UModelBase<TvmType>,
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmValueFixator.kt]: Same about resolver

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmValueFixator.kt (hunk 31 above)
[the remark this answers is not in the document]
Comment (tochilinak) [reply tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmValueFixator.kt]: And since `TvmValueFixator` has resolver as its field, we actually don't need this parameter at all

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/KeyDataTypes.kt [hunk 33]
```diff
@@ -0,0 +1,54 @@
...
+) {
+    fun toExtendedKey(ctx: TvmContext): ExtendedDictKey = ctx.extendDictKey(expr, kind)
+}
+
+data class GuardedTypedDictKey(
+    val symbol: TypedDictKey,
+    val guard: UBoolExpr,
+)
+
+fun TvmState.makeFreshKeyConstant(
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/inputdict/KeyDataTypes.kt]: Maybe `makeFreshKeySymbol`? For me, constant is more like some concrete value (1, 2, ...)

File: tsa-test/src/test/resources/dict/value_overflow.fc [hunk 34]
```diff
@@ -3,7 +3,7 @@
 () main(slice in_msg) {
     var dict = in_msg~load_dict();
 
-    (int i, slice value, var found?) = dict.idict_get_next?(64, -1);
+    (int i, slice value, var found?) = dict.udict_get_next?(64, 0);
```
Comment (tochilinak) [inline tsa-test/src/test/resources/dict/value_overflow.fc]: Maybe return initial test?

**Review by tochilinak — CHANGES_REQUESTED** [review]

File: tsa-core/src/main/kotlin/org/usvm/machine/state/TvmState.kt [hunk 35]
```diff
@@ -215,6 +219,13 @@ class TvmState(
             newState.stack = stack.clone()
             newState.initialInput = initialInput
             newState.isExceptional = isExceptional
+            val lastId = debugInfo.stateIdHistory.lastOrNull()
+            debugInfo.stateIdHistory =
+                if (lastId == null || lastId != id) {
+                    debugInfo.stateIdHistory.add(id)
+                } else {
+                    debugInfo.stateIdHistory
+                }
```
[the remark this answers is not in the document]
Comment (metametamoon) [reply tsa-core/src/main/kotlin/org/usvm/machine/state/TvmState.kt]: True, I'll remove it

File: tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt [hunk 36]
```diff
@@ -1383,33 +1506,79 @@ class TvmDictOperationInterpreter(
...
+        if (isInput) {
+            doSetInstOnInputDict(
+                scope = scope,
+                getOldValue = getOldValue,
+                dictCellRef = dictCellRef,
+                keySort = keySort,
+                keyKind = keyKind,
+                mode = mode,
+                key = key,
+                resultDict = resultDict,
```
Comment (tochilinak) [inline tsa-core/src/main/kotlin/org/usvm/machine/interpreter/TvmDictOperationInterpreter.kt]: Also, `resultDict` can be calculated inside the function to reduce number of arguments

**Review by tochilinak — CHANGES_REQUESTED** [review]
